DEFAULT_INITIAL_PASSWORD = "password1"

ADMIN_GROUP = "Admin"
HR_MANAGER_GROUP = "HR Manager"
PAYROLL_OFFICER_GROUP = "Payroll Officer"
EMPLOYEE_GROUP = "Employee"

ACCOUNT_MANAGER_GROUPS = (ADMIN_GROUP, HR_MANAGER_GROUP)
STAFF_ACCOUNT_ROLES = (HR_MANAGER_GROUP, PAYROLL_OFFICER_GROUP)
