-- LEGACY / STALE — do not run against a live database.
-- Superseded by the Django ORM migrations in accounts/employees/attendance/payroll,
-- which are the actual source of truth for the schema (run via `manage.py migrate`).
-- This file predates those migrations and has since drifted (e.g. Employee gained
-- employment_status, bank_name, bank_account_number, date_of_birth, address; Contract
-- gained contract_type, working_days_per_week, probation_end_date — none reflected here).
-- Kept only for historical reference.
--
-- Original header, for context:
-- HRFlow PostgreSQL schema for Neon
-- Target: PostgreSQL / Neon, DB-first bootstrap for an empty domain schema

BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

DO $$
BEGIN
    IF to_regclass('public.auth_user') IS NULL THEN
        RAISE EXCEPTION
            'public.auth_user is missing. Run Django built-in auth migrations before this HRFlow schema.';
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS employees_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employees_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL
        REFERENCES employees_department(id) ON DELETE RESTRICT,
    title VARCHAR(120) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_position_department_title UNIQUE (department_id, title)
);

CREATE TABLE IF NOT EXISTS employees_employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE
        REFERENCES public.auth_user(id) ON DELETE SET NULL,
    employee_number VARCHAR(30) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    phone VARCHAR(40),
    hire_date DATE NOT NULL,
    department_id BIGINT
        REFERENCES employees_department(id) ON DELETE SET NULL,
    position_id BIGINT
        REFERENCES employees_position(id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employees_contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL
        REFERENCES employees_employee(id) ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE,
    basic_salary NUMERIC(14, 2) NOT NULL,
    fixed_allowances NUMERIC(14, 2) NOT NULL DEFAULT 0,
    working_hours_per_day NUMERIC(4, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_contract_dates CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_contract_salary CHECK (basic_salary >= 0),
    CONSTRAINT ck_contract_allowances CHECK (fixed_allowances >= 0),
    CONSTRAINT ck_contract_working_hours CHECK (
        working_hours_per_day > 0 AND working_hours_per_day <= 24
    ),
    CONSTRAINT ck_contract_status CHECK (status IN ('active', 'inactive', 'ended'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_contract_one_active_per_employee
    ON employees_contract(employee_id)
    WHERE status = 'active';

CREATE TABLE IF NOT EXISTS attendance_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL
        REFERENCES employees_employee(id) ON DELETE RESTRICT,
    work_date DATE NOT NULL,
    check_in TIME,
    check_out TIME,
    worked_hours NUMERIC(6, 2) NOT NULL DEFAULT 0,
    overtime_hours NUMERIC(6, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'present',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attendance_employee_date UNIQUE (employee_id, work_date),
    CONSTRAINT ck_attendance_time_order CHECK (
        check_in IS NULL OR check_out IS NULL OR check_out > check_in
    ),
    CONSTRAINT ck_attendance_hours CHECK (worked_hours >= 0 AND overtime_hours >= 0),
    CONSTRAINT ck_attendance_status CHECK (
        status IN ('present', 'absent', 'leave', 'holiday', 'weekend')
    )
);

CREATE TABLE IF NOT EXISTS attendance_leavetype (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_paid BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance_leaverequest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL
        REFERENCES employees_employee(id) ON DELETE RESTRICT,
    leave_type_id BIGINT NOT NULL
        REFERENCES attendance_leavetype(id) ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    requested_days SMALLINT NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    approved_by_id INTEGER
        REFERENCES public.auth_user(id) ON DELETE SET NULL,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_leave_dates CHECK (end_date >= start_date),
    CONSTRAINT ck_leave_requested_days CHECK (requested_days > 0),
    CONSTRAINT ck_leave_status CHECK (
        status IN ('pending', 'approved', 'rejected', 'cancelled')
    ),
    CONSTRAINT ex_leave_no_active_overlap
        EXCLUDE USING gist (
            employee_id WITH =,
            daterange(start_date, end_date, '[]') WITH &&
        )
        WHERE (status IN ('pending', 'approved'))
);

CREATE TABLE IF NOT EXISTS payroll_bonus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL
        REFERENCES employees_employee(id) ON DELETE RESTRICT,
    amount NUMERIC(14, 2) NOT NULL,
    effective_date DATE NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'approved',
    created_by_id INTEGER
        REFERENCES public.auth_user(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_bonus_amount CHECK (amount >= 0),
    CONSTRAINT ck_bonus_status CHECK (status IN ('pending', 'approved', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS payroll_manualdeduction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL
        REFERENCES employees_employee(id) ON DELETE RESTRICT,
    amount NUMERIC(14, 2) NOT NULL,
    effective_date DATE NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'approved',
    created_by_id INTEGER
        REFERENCES public.auth_user(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_manual_deduction_amount CHECK (amount >= 0),
    CONSTRAINT ck_manual_deduction_status CHECK (
        status IN ('pending', 'approved', 'cancelled')
    )
);

CREATE TABLE IF NOT EXISTS payroll_taxbracket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    min_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    max_amount NUMERIC(14, 2),
    percentage NUMERIC(7, 4) NOT NULL DEFAULT 0,
    fixed_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tax_range CHECK (
        min_amount >= 0 AND (max_amount IS NULL OR max_amount >= min_amount)
    ),
    CONSTRAINT ck_tax_percentage CHECK (percentage >= 0 AND percentage <= 100),
    CONSTRAINT ck_tax_fixed_amount CHECK (fixed_amount >= 0)
);

CREATE TABLE IF NOT EXISTS payroll_payroll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month SMALLINT NOT NULL,
    year SMALLINT NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    calculation_version VARCHAR(30) NOT NULL DEFAULT 'v1',
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    total_gross NUMERIC(16, 2) NOT NULL DEFAULT 0,
    total_deductions NUMERIC(16, 2) NOT NULL DEFAULT 0,
    total_net NUMERIC(16, 2) NOT NULL DEFAULT 0,
    created_by_id INTEGER NOT NULL
        REFERENCES public.auth_user(id) ON DELETE RESTRICT,
    reviewed_by_id INTEGER
        REFERENCES public.auth_user(id) ON DELETE SET NULL,
    approved_by_id INTEGER
        REFERENCES public.auth_user(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payroll_month_year UNIQUE (month, year),
    CONSTRAINT ck_payroll_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_payroll_year CHECK (year BETWEEN 2000 AND 9999),
    CONSTRAINT ck_payroll_period CHECK (
        period_start = make_date(year, month, 1)
        AND period_end = (make_date(year, month, 1) + INTERVAL '1 month - 1 day')::date
    ),
    CONSTRAINT ck_payroll_currency CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payroll_status CHECK (
        status IN ('draft', 'calculated', 'reviewed', 'approved', 'paid')
    ),
    CONSTRAINT ck_payroll_totals CHECK (
        total_gross >= 0 AND total_deductions >= 0 AND total_net >= 0
    )
);

CREATE TABLE IF NOT EXISTS payroll_payrollitem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL
        REFERENCES payroll_payroll(id) ON DELETE RESTRICT,
    employee_id BIGINT NOT NULL
        REFERENCES employees_employee(id) ON DELETE RESTRICT,
    contract_id BIGINT NOT NULL
        REFERENCES employees_contract(id) ON DELETE RESTRICT,
    employee_number VARCHAR(30) NOT NULL,
    employee_name VARCHAR(220) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    calculation_version VARCHAR(30) NOT NULL,
    contract_start_date DATE NOT NULL,
    contract_end_date DATE,
    working_hours_per_day NUMERIC(4, 2) NOT NULL,
    basic_salary NUMERIC(14, 2) NOT NULL,
    allowances NUMERIC(14, 2) NOT NULL DEFAULT 0,
    daily_rate NUMERIC(14, 2) NOT NULL,
    hourly_rate NUMERIC(14, 2) NOT NULL,
    overtime_multiplier NUMERIC(6, 3) NOT NULL,
    overtime_hours NUMERIC(8, 2) NOT NULL DEFAULT 0,
    overtime_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    bonus_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    absence_days SMALLINT NOT NULL DEFAULT 0,
    absence_deduction NUMERIC(14, 2) NOT NULL DEFAULT 0,
    unpaid_leave_days SMALLINT NOT NULL DEFAULT 0,
    unpaid_leave_deduction NUMERIC(14, 2) NOT NULL DEFAULT 0,
    manual_deduction_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    tax_percentage NUMERIC(7, 4) NOT NULL DEFAULT 0,
    tax_fixed_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    gross_salary NUMERIC(14, 2) NOT NULL,
    total_deductions NUMERIC(14, 2) NOT NULL,
    net_salary NUMERIC(14, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payroll_item_employee UNIQUE (payroll_id, employee_id),
    CONSTRAINT ck_payroll_item_currency CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payroll_item_nonnegative CHECK (
        working_hours_per_day > 0
        AND basic_salary >= 0
        AND allowances >= 0
        AND daily_rate >= 0
        AND hourly_rate >= 0
        AND overtime_multiplier >= 0
        AND overtime_hours >= 0
        AND overtime_amount >= 0
        AND bonus_amount >= 0
        AND absence_days >= 0
        AND absence_deduction >= 0
        AND unpaid_leave_days >= 0
        AND unpaid_leave_deduction >= 0
        AND manual_deduction_amount >= 0
        AND tax_percentage >= 0
        AND tax_percentage <= 100
        AND tax_fixed_amount >= 0
        AND tax_amount >= 0
        AND gross_salary >= 0
        AND total_deductions >= 0
        AND net_salary >= 0
    )
);

CREATE TABLE IF NOT EXISTS payroll_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_item_id BIGINT NOT NULL UNIQUE
        REFERENCES payroll_payrollitem(id) ON DELETE RESTRICT,
    amount NUMERIC(14, 2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_method VARCHAR(40) NOT NULL,
    reference_number VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'completed',
    created_by_id INTEGER
        REFERENCES public.auth_user(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_payment_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_status CHECK (status = 'completed')
);

CREATE INDEX IF NOT EXISTS idx_position_department
    ON employees_position(department_id);
CREATE INDEX IF NOT EXISTS idx_employee_department
    ON employees_employee(department_id);
CREATE INDEX IF NOT EXISTS idx_employee_position
    ON employees_employee(position_id);
CREATE INDEX IF NOT EXISTS idx_contract_employee
    ON employees_contract(employee_id);
CREATE INDEX IF NOT EXISTS idx_attendance_employee_date
    ON attendance_attendance(employee_id, work_date);
CREATE INDEX IF NOT EXISTS idx_leave_employee_dates
    ON attendance_leaverequest(employee_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_bonus_employee_date
    ON payroll_bonus(employee_id, effective_date);
CREATE INDEX IF NOT EXISTS idx_deduction_employee_date
    ON payroll_manualdeduction(employee_id, effective_date);
CREATE INDEX IF NOT EXISTS idx_payroll_item_payroll
    ON payroll_payrollitem(payroll_id);
CREATE INDEX IF NOT EXISTS idx_payroll_item_employee
    ON payroll_payrollitem(employee_id);

CREATE OR REPLACE FUNCTION hrflow_guard_payroll_item_snapshot()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    payroll_status VARCHAR(20);
BEGIN
    SELECT status
      INTO payroll_status
      FROM payroll_payroll
     WHERE id = COALESCE(NEW.payroll_id, OLD.payroll_id);

    IF payroll_status IN ('approved', 'paid') THEN
        RAISE EXCEPTION 'PayrollItem snapshots cannot change after payroll approval';
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_guard_payroll_item_snapshot ON payroll_payrollitem;
CREATE TRIGGER trg_guard_payroll_item_snapshot
BEFORE INSERT OR UPDATE OR DELETE ON payroll_payrollitem
FOR EACH ROW
EXECUTE FUNCTION hrflow_guard_payroll_item_snapshot();

CREATE OR REPLACE FUNCTION hrflow_validate_completed_payment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    expected_net NUMERIC(14, 2);
    parent_status VARCHAR(20);
BEGIN
    SELECT item.net_salary, payroll.status
      INTO expected_net, parent_status
      FROM payroll_payrollitem AS item
      JOIN payroll_payroll AS payroll ON payroll.id = item.payroll_id
     WHERE item.id = NEW.payroll_item_id;

    IF parent_status <> 'approved' THEN
        RAISE EXCEPTION 'Payment requires an approved payroll';
    END IF;

    IF NEW.amount <> expected_net THEN
        RAISE EXCEPTION 'Payment amount must equal PayrollItem net salary';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_completed_payment ON payroll_payment;
CREATE TRIGGER trg_validate_completed_payment
BEFORE INSERT OR UPDATE ON payroll_payment
FOR EACH ROW
EXECUTE FUNCTION hrflow_validate_completed_payment();

COMMENT ON TABLE payroll_payrollitem IS
    'Immutable employee payroll snapshot; historical payslips render from these saved values.';
COMMENT ON COLUMN attendance_attendance.overtime_hours IS
    'Attendance fact only. Payroll converts approved hours into money.';

COMMIT;
