# Generated by Django 5.2.17 on 2026-09-01 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='bonus',
            name='bonus_amount_gte_0',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='bonus_amount_gte_0', violation_error_message='Amount cannot be negative.'),
        ),
        migrations.AlterConstraint(
            model_name='manualdeduction',
            name='manualdeduction_amount_gte_0',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='manualdeduction_amount_gte_0', violation_error_message='Amount cannot be negative.'),
        ),
        migrations.AlterConstraint(
            model_name='taxbracket',
            name='taxbracket_min_amount_gte_0',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gte', 0)), name='taxbracket_min_amount_gte_0', violation_error_message='Min amount cannot be negative.'),
        ),
        migrations.AlterConstraint(
            model_name='taxbracket',
            name='taxbracket_percentage_gte_0',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0)), name='taxbracket_percentage_gte_0', violation_error_message='Percentage cannot be negative.'),
        ),
        migrations.AlterConstraint(
            model_name='taxbracket',
            name='taxbracket_max_amount_gte_min_amount',
            constraint=models.CheckConstraint(condition=models.Q(('max_amount__isnull', True), ('max_amount__gte', models.F('min_amount')), _connector='OR'), name='taxbracket_max_amount_gte_min_amount', violation_error_message='Max amount must be greater than or equal to min amount.'),
        ),
    ]
