# Generated by Django 5.2.17 on 2026-09-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_position_options_and_more'),
        ('payroll', '0002_alter_bonus_bonus_amount_gte_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollitem',
            name='calculation_inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='calculation_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='employees.contract'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='currency_code',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='employee_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=201),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='employee_number_snapshot',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='payrollitem',
            constraint=models.CheckConstraint(condition=models.Q(('basic_salary__gte', 0), ('allowances__gte', 0), ('overtime_hours__gte', 0), ('overtime_amount__gte', 0), ('bonus_amount__gte', 0), ('gross_salary__gte', 0), ('absence_days__gte', 0), ('absence_deduction__gte', 0), ('unpaid_leave_days__gte', 0), ('unpaid_leave_deduction__gte', 0), ('manual_deduction_amount__gte', 0), ('tax_amount__gte', 0), ('total_deductions__gte', 0), ('net_salary__gte', 0)), name='payrollitem_nonnegative_values'),
        ),
    ]
